name: Run UV Commands on Commit

on:
  push:
    branches:
      - '**'

jobs:
  run-uv-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install UV
      run: |
        pip install uv

    - name: Run UV Sync
      run: |
        uv sync


    - name: Set Environment Variables
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV 



    - name: Run Pre-commit
      run: |
        uv run run_tools_server.py & uv run run_main_server.py & sleep 10 && uvx pre-commit run 
